config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index' #devise

  get 'home/index'
  get '/' => 'home#index'
  get '/about' => 'pages#about'
  get '/terms' => 'pages#terms'

  resources :articles do
    resources :comments
  end
  
  resource :contacts, only: [:new, :create], path_names: { :new => ''} 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  # belongs_to :user
  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 4000 }

  def subject
    title
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true, length: { maximum: 4000 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @article = Article.all
    @user = User.all
  end

  def show
    @article = Article.find(params[:id])    
    @user = User.all
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.valid?
      @article.save
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'    #returns action edit (def edit), saving @article variable
    end 
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  
  private

  def article_params
    params.require(:article).permit(:title, :text, :user_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.commenter = current_user.username
    @comment.save
    redirect_to article_path(@article)
  end
 
  def destroy
    @user = User.all
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @article = Article.all
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
def about
end

def terms
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def show
  end
  def new
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>    

    <header>
      <ul class='menu'>
      <%= link_to 'home', home_index_path %> | <%= link_to 'articles', articles_path %> | <a href="/contacts">contact</a> | <a href="/about">about</a> | <a href="/terms">terms</a> | <% if user_signed_in? %> <b><%= link_to "#{current_user.username}", edit_user_registration_path %></b> | <%= link_to 'logout', destroy_user_session_path, method: :delete %> <% else %> <%= link_to 'login', new_user_session_path %> <% end %>
      </ul>
    </header>

    <%= yield %>

    <div align=center><br />
    <p class="notice"><i><%= notice %></i></p>
    <p class="alert"><%= alert %></p>
    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<h2>about</h2>

app/views/pages/terms.html.erb
<h2>terms</h2>